### PR TITLE
Add support for Python 3 and some code refactoring for pep8

### PR DESCRIPTION
**Pull request by SambaDemon**
Add support for python 3.

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @SambaDemon!  Could you also please add yourself to CONTRIBUTORS.txt as part of this PR?

**Comment by SambaDemon** [comment]
Ok. I will do it.

**Comment by SambaDemon** [comment]
Done. I add myself to CONTRIBUTORS.txt.

**Comment by rfk** [comment]
thanks!

**Comment by rfk** [comment]
I've release v0.3.0 with these changes

**Pull request merged**
